name: generator
on:
  workflow_dispatch:
jobs:
  openai_completion:
    runs-on: ubuntu-latest
    name: OpenAI
    steps:
      - uses: austenstone/openai-completion-action@main
        name: OpenAI Completion
        id: openai_completion
        with:
          prompt: "act as a software expert in team topologies and write a tweets that explain the importance of platform teams"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - uses: actions/github-script@v5
        name: Print the response text
        with:
          script:  console.log(JSON.parse('${{ steps.openai_completion.outputs.response }}'.replace(/\\/g,"").replace(/""/g,'"')).choices[0].message.content)
