name: generator
on:
  workflow_dispatch:
jobs:
  openai_completion:
    runs-on: ubuntu-latest
    name: OpenAI
    steps:
      - uses: austenstone/openai-completion-action@main
        name: OpenAI Completion
        id: openai_completion
        with:
          prompt: "write a tweets regarding the importance of platform teams"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - uses: actions/github-script@v5
        name: Print the response text
        with:
          script:  console.log(JSON.parse(`${{ steps.openai_completion.outputs.response }}`.replace(/\\/g,"").replace(/""/g,'"')).choices[0].message.content)
      - name: Create a Trello Card
        uses: TrisNol/trello-create-card-action@main
        with:
          api_key: ${{ secrets.TRELLO_API_KEY }}
          token: ${{ secrets.TRELLO_TOKEN }}
          board_id: "1Z2Y5C9q"
          list_name: "Backlog"
          card_name: ${{ JSON.parse(`${{ steps.openai_completion.outputs.response }}`.replace(/\\/g,"").replace(/""/g,'"')).choices[0].message.content }}
          card_description: ""
